services:
  app:
    image: myapp:latest
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - pg
      - redis
    networks:
      - backend_network
    volumes:
      - videos:/app/videos

  pg:
    image: "postgres"
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_network

  redis:
    image: "redis:latest"
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend_network

  worker:
    image: myapp:latest
    command: celery -A app.api.utils worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - app
      - redis
    networks:
      - backend_network
    volumes:
      - videos:/app/videos

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis
      - app
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  pgdata:
  redis_data:
  videos: